-- -------------------------------------------------------------
-- 
-- File Name: /shares/bulk/eserlis/simulink_mpc/codegen/fcs_mpc_v4/hdlsrc/fcs_mpc_v4.vhd
-- Created: 2026-07-28 15:03:49
-- 
-- Generated by MATLAB 9.11, MATLAB Coder 5.3 and HDL Coder 3.19
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fcs_mpc_v4
-- Source Path: fcs_mpc_v4
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fcs_mpc_v4_pkg.ALL;

ENTITY fcs_mpc_v4 IS
  PORT( x                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        y                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        psi                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        v                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        ref_x                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        ref_y                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        ref_v                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        accel_cmd                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        steer_cmd                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END fcs_mpc_v4;


ARCHITECTURE rtl OF fcs_mpc_v4 IS

  -- Constants
  CONSTANT nc                             : vector_of_signed8(0 TO 16) := 
    (to_signed(16#00#, 8), X"FE", to_signed(16#02#, 8), X"FC", to_signed(16#04#, 8), X"F9", to_signed(16#07#, 8),
     X"F6", to_signed(16#0A#, 8), X"F2", to_signed(16#0E#, 8), X"EE", to_signed(16#12#, 8),
     X"EA", to_signed(16#16#, 8), X"E6", to_signed(16#1A#, 8));  -- int8 [17]
  CONSTANT nc_0                           : vector_of_signed8(0 TO 7) := 
    (to_signed(16#00#, 8), to_signed(16#14#, 8), to_signed(16#0A#, 8), to_signed(16#04#, 8),
     X"FC", X"F6", X"EC", X"E1");  -- int8 [8]
  CONSTANT nc_1_1                         : vector_of_signed8(0 TO 255) := 
    (to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7E#, 8), to_signed(16#7E#, 8), to_signed(16#7D#, 8), to_signed(16#7C#, 8), to_signed(16#7C#, 8),
     to_signed(16#7B#, 8), to_signed(16#7A#, 8), to_signed(16#79#, 8), to_signed(16#78#, 8), to_signed(16#77#, 8),
     to_signed(16#76#, 8), to_signed(16#74#, 8), to_signed(16#73#, 8), to_signed(16#72#, 8), to_signed(16#70#, 8),
     to_signed(16#6F#, 8), to_signed(16#6D#, 8), to_signed(16#6B#, 8), to_signed(16#6A#, 8), to_signed(16#68#, 8),
     to_signed(16#66#, 8), to_signed(16#64#, 8), to_signed(16#62#, 8), to_signed(16#60#, 8), to_signed(16#5E#, 8),
     to_signed(16#5C#, 8), to_signed(16#5A#, 8), to_signed(16#58#, 8), to_signed(16#55#, 8), to_signed(16#53#, 8),
     to_signed(16#51#, 8), to_signed(16#4E#, 8), to_signed(16#4C#, 8), to_signed(16#49#, 8), to_signed(16#47#, 8),
     to_signed(16#44#, 8), to_signed(16#41#, 8), to_signed(16#3F#, 8), to_signed(16#3C#, 8), to_signed(16#39#, 8),
     to_signed(16#36#, 8), to_signed(16#33#, 8), to_signed(16#31#, 8), to_signed(16#2E#, 8), to_signed(16#2B#, 8),
     to_signed(16#28#, 8), to_signed(16#25#, 8), to_signed(16#22#, 8), to_signed(16#1F#, 8), to_signed(16#1C#, 8),
     to_signed(16#19#, 8), to_signed(16#16#, 8), to_signed(16#13#, 8), to_signed(16#10#, 8), to_signed(16#0C#, 8),
     to_signed(16#09#, 8), to_signed(16#06#, 8), to_signed(16#03#, 8), to_signed(16#00#, 8), to_signed(16#00#, 8),
     X"FD", X"FA", X"F7", X"F4", X"F0", X"ED", X"EA", X"E7", X"E4", X"E1", X"DE", X"DB", X"D8", X"D5", X"D2", X"CF", X"CD", X"CA", X"C7", X"C4", X"C1", X"BF", X"BC", X"B9", X"B7", X"B4", X"B2", X"AF", X"AD", X"AB", X"A8", X"A6", X"A4", X"A2", X"A0", X"9E", X"9C", X"9A", X"98", X"96", X"95", X"93", X"91", X"90", X"8E", X"8D", X"8C", X"8A", X"89", X"88", X"87", X"86", X"85", X"84", X"84", X"83", X"82", X"82", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"82", X"82", X"83", X"84", X"84", X"85", X"86", X"87", X"88", X"89", X"8A", X"8C", X"8D", X"8E", X"90", X"91", X"93", X"95", X"96", X"98", X"9A", X"9C", X"9E", X"A0", X"A2", X"A4", X"A6", X"A8", X"AB", X"AD", X"AF", X"B2", X"B4", X"B7", X"B9", X"BC", X"BF", X"C1", X"C4", X"C7", X"CA", X"CD", X"CF", X"D2", X"D5", X"D8", X"DB", X"DE", X"E1", X"E4", X"E7", X"EA", X"ED", X"F0", X"F4", X"F7", X"FA", X"FD", to_signed(16#00#, 8),
     to_signed(16#00#, 8), to_signed(16#03#, 8), to_signed(16#06#, 8), to_signed(16#09#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#13#, 8), to_signed(16#16#, 8), to_signed(16#19#, 8), to_signed(16#1C#, 8),
     to_signed(16#1F#, 8), to_signed(16#22#, 8), to_signed(16#25#, 8), to_signed(16#28#, 8), to_signed(16#2B#, 8),
     to_signed(16#2E#, 8), to_signed(16#31#, 8), to_signed(16#33#, 8), to_signed(16#36#, 8), to_signed(16#39#, 8),
     to_signed(16#3C#, 8), to_signed(16#3F#, 8), to_signed(16#41#, 8), to_signed(16#44#, 8), to_signed(16#47#, 8),
     to_signed(16#49#, 8), to_signed(16#4C#, 8), to_signed(16#4E#, 8), to_signed(16#51#, 8), to_signed(16#53#, 8),
     to_signed(16#55#, 8), to_signed(16#58#, 8), to_signed(16#5A#, 8), to_signed(16#5C#, 8), to_signed(16#5E#, 8),
     to_signed(16#60#, 8), to_signed(16#62#, 8), to_signed(16#64#, 8), to_signed(16#66#, 8), to_signed(16#68#, 8),
     to_signed(16#6A#, 8), to_signed(16#6B#, 8), to_signed(16#6D#, 8), to_signed(16#6F#, 8), to_signed(16#70#, 8),
     to_signed(16#72#, 8), to_signed(16#73#, 8), to_signed(16#74#, 8), to_signed(16#76#, 8), to_signed(16#77#, 8),
     to_signed(16#78#, 8), to_signed(16#79#, 8), to_signed(16#7A#, 8), to_signed(16#7B#, 8), to_signed(16#7C#, 8),
     to_signed(16#7C#, 8), to_signed(16#7D#, 8), to_signed(16#7E#, 8), to_signed(16#7E#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8));  -- int8 [256]
  CONSTANT nc_2                           : vector_of_signed8(0 TO 255) := 
    (to_signed(16#00#, 8), to_signed(16#03#, 8), to_signed(16#06#, 8), to_signed(16#09#, 8), to_signed(16#0C#, 8),
     to_signed(16#10#, 8), to_signed(16#13#, 8), to_signed(16#16#, 8), to_signed(16#19#, 8), to_signed(16#1C#, 8),
     to_signed(16#1F#, 8), to_signed(16#22#, 8), to_signed(16#25#, 8), to_signed(16#28#, 8), to_signed(16#2B#, 8),
     to_signed(16#2E#, 8), to_signed(16#31#, 8), to_signed(16#33#, 8), to_signed(16#36#, 8), to_signed(16#39#, 8),
     to_signed(16#3C#, 8), to_signed(16#3F#, 8), to_signed(16#41#, 8), to_signed(16#44#, 8), to_signed(16#47#, 8),
     to_signed(16#49#, 8), to_signed(16#4C#, 8), to_signed(16#4E#, 8), to_signed(16#51#, 8), to_signed(16#53#, 8),
     to_signed(16#55#, 8), to_signed(16#58#, 8), to_signed(16#5A#, 8), to_signed(16#5C#, 8), to_signed(16#5E#, 8),
     to_signed(16#60#, 8), to_signed(16#62#, 8), to_signed(16#64#, 8), to_signed(16#66#, 8), to_signed(16#68#, 8),
     to_signed(16#6A#, 8), to_signed(16#6B#, 8), to_signed(16#6D#, 8), to_signed(16#6F#, 8), to_signed(16#70#, 8),
     to_signed(16#72#, 8), to_signed(16#73#, 8), to_signed(16#74#, 8), to_signed(16#76#, 8), to_signed(16#77#, 8),
     to_signed(16#78#, 8), to_signed(16#79#, 8), to_signed(16#7A#, 8), to_signed(16#7B#, 8), to_signed(16#7C#, 8),
     to_signed(16#7C#, 8), to_signed(16#7D#, 8), to_signed(16#7E#, 8), to_signed(16#7E#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7E#, 8),
     to_signed(16#7E#, 8), to_signed(16#7D#, 8), to_signed(16#7C#, 8), to_signed(16#7C#, 8), to_signed(16#7B#, 8),
     to_signed(16#7A#, 8), to_signed(16#79#, 8), to_signed(16#78#, 8), to_signed(16#77#, 8), to_signed(16#76#, 8),
     to_signed(16#74#, 8), to_signed(16#73#, 8), to_signed(16#72#, 8), to_signed(16#70#, 8), to_signed(16#6F#, 8),
     to_signed(16#6D#, 8), to_signed(16#6B#, 8), to_signed(16#6A#, 8), to_signed(16#68#, 8), to_signed(16#66#, 8),
     to_signed(16#64#, 8), to_signed(16#62#, 8), to_signed(16#60#, 8), to_signed(16#5E#, 8), to_signed(16#5C#, 8),
     to_signed(16#5A#, 8), to_signed(16#58#, 8), to_signed(16#55#, 8), to_signed(16#53#, 8), to_signed(16#51#, 8),
     to_signed(16#4E#, 8), to_signed(16#4C#, 8), to_signed(16#49#, 8), to_signed(16#47#, 8), to_signed(16#44#, 8),
     to_signed(16#41#, 8), to_signed(16#3F#, 8), to_signed(16#3C#, 8), to_signed(16#39#, 8), to_signed(16#36#, 8),
     to_signed(16#33#, 8), to_signed(16#31#, 8), to_signed(16#2E#, 8), to_signed(16#2B#, 8), to_signed(16#28#, 8),
     to_signed(16#25#, 8), to_signed(16#22#, 8), to_signed(16#1F#, 8), to_signed(16#1C#, 8), to_signed(16#19#, 8),
     to_signed(16#16#, 8), to_signed(16#13#, 8), to_signed(16#10#, 8), to_signed(16#0C#, 8), to_signed(16#09#, 8),
     to_signed(16#06#, 8), to_signed(16#03#, 8), to_signed(16#00#, 8), to_signed(16#00#, 8),
     X"FD", X"FA", X"F7", X"F4", X"F0", X"ED", X"EA", X"E7", X"E4", X"E1", X"DE", X"DB", X"D8", X"D5", X"D2", X"CF", X"CD", X"CA", X"C7", X"C4", X"C1", X"BF", X"BC", X"B9", X"B7", X"B4", X"B2", X"AF", X"AD", X"AB", X"A8", X"A6", X"A4", X"A2", X"A0", X"9E", X"9C", X"9A", X"98", X"96", X"95", X"93", X"91", X"90", X"8E", X"8D", X"8C", X"8A", X"89", X"88", X"87", X"86", X"85", X"84", X"84", X"83", X"82", X"82", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"81", X"82", X"82", X"83", X"84", X"84", X"85", X"86", X"87", X"88", X"89", X"8A", X"8C", X"8D", X"8E", X"90", X"91", X"93", X"95", X"96", X"98", X"9A", X"9C", X"9E", X"A0", X"A2", X"A4", X"A6", X"A8", X"AB", X"AD", X"AF", X"B2", X"B4", X"B7", X"B9", X"BC", X"BF", X"C1", X"C4", X"C7", X"CA", X"CD", X"CF", X"D2", X"D5", X"D8", X"DB", X"DE", X"E1", X"E4", X"E7", X"EA", X"ED", X"F0", X"F4", X"F7", X"FA", X"FD", to_signed(16#00#, 8));  -- int8 [256]

  -- Signals
  SIGNAL x_signed                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL y_signed                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL psi_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL v_signed                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL ref_x_signed                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL ref_y_signed                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL ref_v_signed                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL accel_cmd_tmp                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL steer_cmd_tmp                    : signed(15 DOWNTO 0);  -- int16

BEGIN
  x_signed <= signed(x);

  y_signed <= signed(y);

  psi_signed <= signed(psi);

  v_signed <= signed(v);

  ref_x_signed <= signed(ref_x);

  ref_y_signed <= signed(ref_y);

  ref_v_signed <= signed(ref_v);

  fcs_mpc_v4_1_output : PROCESS (psi_signed, ref_v_signed, ref_x_signed, ref_y_signed, v_signed, x_signed,
       y_signed)
    VARIABLE c : signed(15 DOWNTO 0);
    VARIABLE best_str : signed(15 DOWNTO 0);
    VARIABLE best_acc : signed(15 DOWNTO 0);
    VARIABLE lut_idx : signed(15 DOWNTO 0);
    VARIABLE tmp : signed(15 DOWNTO 0);
    VARIABLE err_x : signed(15 DOWNTO 0);
    VARIABLE err_y : signed(15 DOWNTO 0);
    VARIABLE A : signed(15 DOWNTO 0);
    VARIABLE minA : signed(15 DOWNTO 0);
    VARIABLE v_next : signed(15 DOWNTO 0);
    VARIABLE ov : signed(15 DOWNTO 0);
    VARIABLE B : signed(15 DOWNTO 0);
    VARIABLE minB : signed(15 DOWNTO 0);
    VARIABLE mul_temp : vector_of_signed24(0 TO 16);
    VARIABLE cast : vector_of_signed16(0 TO 16);
    VARIABLE add_temp : vector_of_signed17(0 TO 16);
    VARIABLE cast_0 : vector_of_signed16(0 TO 16);
    VARIABLE cast_1 : vector_of_signed32(0 TO 16);
    VARIABLE add_cast : vector_of_signed16(0 TO 16);
    VARIABLE t_0 : vector_of_signed33(0 TO 16);
    VARIABLE mul_temp_0 : vector_of_signed24(0 TO 16);
    VARIABLE cast_2 : vector_of_signed16(0 TO 16);
    VARIABLE add_temp_0 : vector_of_signed17(0 TO 16);
    VARIABLE sub_cast : vector_of_signed16(0 TO 16);
    VARIABLE sub_cast_0 : vector_of_signed17(0 TO 16);
    VARIABLE sub_temp : vector_of_signed17(0 TO 16);
    VARIABLE add_temp_1 : vector_of_signed17(0 TO 7);
    VARIABLE err_x_0 : vector_of_signed17(0 TO 16);
    VARIABLE mul_temp_1 : vector_of_signed24(0 TO 16);
    VARIABLE cast_3 : vector_of_signed16(0 TO 16);
    VARIABLE add_temp_2 : vector_of_signed17(0 TO 16);
    VARIABLE sub_cast_1 : vector_of_signed16(0 TO 16);
    VARIABLE sub_cast_2 : vector_of_signed17(0 TO 16);
    VARIABLE sub_temp_0 : vector_of_signed17(0 TO 16);
    VARIABLE sub_temp_1 : vector_of_signed17(0 TO 7);
    VARIABLE err_y_0 : vector_of_signed17(0 TO 16);
    VARIABLE add_temp_3 : vector_of_signed17(0 TO 16);
    VARIABLE cast_4 : vector_of_signed16(0 TO 16);
    VARIABLE mul_temp_2 : vector_of_signed32(0 TO 16);
    VARIABLE add_cast_0 : vector_of_signed16(0 TO 16);
    VARIABLE add_cast_1 : vector_of_signed17(0 TO 16);
    VARIABLE add_cast_2 : vector_of_signed48(0 TO 16);
    VARIABLE add_cast_3 : vector_of_signed16(0 TO 16);
    VARIABLE add_temp_4 : vector_of_signed17(0 TO 16);
    VARIABLE mul_temp_3 : vector_of_signed48(0 TO 7);
    VARIABLE sub_cast_3 : vector_of_signed16(0 TO 7);
    VARIABLE sub_cast_4 : vector_of_signed32(0 TO 7);
    VARIABLE sub_cast_5 : vector_of_signed16(0 TO 7);
    VARIABLE sub_cast_6 : vector_of_signed17(0 TO 7);
    VARIABLE sub_temp_2 : vector_of_signed17(0 TO 7);
  BEGIN
    lut_idx := to_signed(16#0000#, 16);
    err_x := to_signed(16#0000#, 16);
    err_y := to_signed(16#0000#, 16);
    v_next := to_signed(16#0000#, 16);
    ov := to_signed(16#0000#, 16);
    A := to_signed(16#0000#, 16);
    B := to_signed(16#0000#, 16);
    tmp := to_signed(16#0000#, 16);
    --HDL code generation from MATLAB function: fcs_mpc_v4
    -- Area/timing-optimised restatement of fcs_mpc_v3. Bit-identical outputs.
    -- cost(s,a) = A(s) + B(a) is separable, so 17 kinematic cones + 8 speed
    -- terms replace 136 full evaluations, and the 136-deep argmin becomes two
    -- independent first-minimum scans (17 and 8).
    -- --- Steer branch: 17 cones (kinematics + LUT + distance + effort) ---
    c := SHIFT_RIGHT(v_signed, 4);
    minA := to_signed(16#7FFF#, 16);
    best_str := to_signed(16#0000#, 16);

    FOR s_idx IN 0 TO 16 LOOP
      mul_temp(s_idx) := v_signed * nc(s_idx);
      IF (mul_temp(s_idx)(23) = '0') AND (mul_temp(s_idx)(22 DOWNTO 15) /= "00000000") THEN 
        cast(s_idx) := X"7FFF";
      ELSIF (mul_temp(s_idx)(23) = '1') AND (mul_temp(s_idx)(22 DOWNTO 15) /= "11111111") THEN 
        cast(s_idx) := X"8000";
      ELSE 
        cast(s_idx) := mul_temp(s_idx)(15 DOWNTO 0);
      END IF;
      add_temp(s_idx) := resize(psi_signed, 17) + resize(SHIFT_RIGHT(cast(s_idx), 9), 17);
      IF (add_temp(s_idx)(16) = '0') AND (add_temp(s_idx)(15) /= '0') THEN 
        cast_0(s_idx) := X"7FFF";
      ELSIF (add_temp(s_idx)(16) = '1') AND (add_temp(s_idx)(15) /= '1') THEN 
        cast_0(s_idx) := X"8000";
      ELSE 
        cast_0(s_idx) := add_temp(s_idx)(15 DOWNTO 0);
      END IF;
      cast_1(s_idx) := resize(cast_0(s_idx), 32) AND to_signed(16#000000FF#, 32);
      add_cast(s_idx) := cast_1(s_idx)(15 DOWNTO 0);
      lut_idx := add_cast(s_idx) + 1;
      IF nc(s_idx) < to_signed(16#00000000#, 8) THEN 
        t_0(s_idx) :=  - (resize(nc(s_idx), 33));
        tmp := t_0(s_idx)(15 DOWNTO 0);
      ELSE 
        tmp := resize(nc(s_idx), 16);
      END IF;
      mul_temp_0(s_idx) := c * nc_1_1(to_integer(resize(lut_idx, 32) - 1));
      IF (mul_temp_0(s_idx)(23) = '0') AND (mul_temp_0(s_idx)(22 DOWNTO 15) /= "00000000") THEN 
        cast_2(s_idx) := X"7FFF";
      ELSIF (mul_temp_0(s_idx)(23) = '1') AND (mul_temp_0(s_idx)(22 DOWNTO 15) /= "11111111") THEN 
        cast_2(s_idx) := X"8000";
      ELSE 
        cast_2(s_idx) := mul_temp_0(s_idx)(15 DOWNTO 0);
      END IF;
      add_temp_0(s_idx) := resize(x_signed, 17) + resize(SHIFT_RIGHT(cast_2(s_idx), 5), 17);
      IF (add_temp_0(s_idx)(16) = '0') AND (add_temp_0(s_idx)(15) /= '0') THEN 
        sub_cast(s_idx) := X"7FFF";
      ELSIF (add_temp_0(s_idx)(16) = '1') AND (add_temp_0(s_idx)(15) /= '1') THEN 
        sub_cast(s_idx) := X"8000";
      ELSE 
        sub_cast(s_idx) := add_temp_0(s_idx)(15 DOWNTO 0);
      END IF;
      sub_cast_0(s_idx) := resize(sub_cast(s_idx), 17);
      sub_temp(s_idx) := sub_cast_0(s_idx) - resize(ref_x_signed, 17);
      IF (sub_temp(s_idx)(16) = '0') AND (sub_temp(s_idx)(15) /= '0') THEN 
        err_x := X"7FFF";
      ELSIF (sub_temp(s_idx)(16) = '1') AND (sub_temp(s_idx)(15) /= '1') THEN 
        err_x := X"8000";
      ELSE 
        err_x := sub_temp(s_idx)(15 DOWNTO 0);
      END IF;
      IF err_x < to_signed(16#00000000#, 16) THEN 
        err_x_0(s_idx) :=  - (resize(err_x, 17));
        IF (err_x_0(s_idx)(16) = '0') AND (err_x_0(s_idx)(15) /= '0') THEN 
          err_x := X"7FFF";
        ELSIF (err_x_0(s_idx)(16) = '1') AND (err_x_0(s_idx)(15) /= '1') THEN 
          err_x := X"8000";
        ELSE 
          err_x := err_x_0(s_idx)(15 DOWNTO 0);
        END IF;
      END IF;
      IF err_x > to_signed(16#000003E8#, 16) THEN 
        err_x := to_signed(16#03E8#, 16);
      END IF;
      mul_temp_1(s_idx) := c * nc_2(to_integer(resize(lut_idx, 32) - 1));
      IF (mul_temp_1(s_idx)(23) = '0') AND (mul_temp_1(s_idx)(22 DOWNTO 15) /= "00000000") THEN 
        cast_3(s_idx) := X"7FFF";
      ELSIF (mul_temp_1(s_idx)(23) = '1') AND (mul_temp_1(s_idx)(22 DOWNTO 15) /= "11111111") THEN 
        cast_3(s_idx) := X"8000";
      ELSE 
        cast_3(s_idx) := mul_temp_1(s_idx)(15 DOWNTO 0);
      END IF;
      add_temp_2(s_idx) := resize(y_signed, 17) + resize(SHIFT_RIGHT(cast_3(s_idx), 5), 17);
      IF (add_temp_2(s_idx)(16) = '0') AND (add_temp_2(s_idx)(15) /= '0') THEN 
        sub_cast_1(s_idx) := X"7FFF";
      ELSIF (add_temp_2(s_idx)(16) = '1') AND (add_temp_2(s_idx)(15) /= '1') THEN 
        sub_cast_1(s_idx) := X"8000";
      ELSE 
        sub_cast_1(s_idx) := add_temp_2(s_idx)(15 DOWNTO 0);
      END IF;
      sub_cast_2(s_idx) := resize(sub_cast_1(s_idx), 17);
      sub_temp_0(s_idx) := sub_cast_2(s_idx) - resize(ref_y_signed, 17);
      IF (sub_temp_0(s_idx)(16) = '0') AND (sub_temp_0(s_idx)(15) /= '0') THEN 
        err_y := X"7FFF";
      ELSIF (sub_temp_0(s_idx)(16) = '1') AND (sub_temp_0(s_idx)(15) /= '1') THEN 
        err_y := X"8000";
      ELSE 
        err_y := sub_temp_0(s_idx)(15 DOWNTO 0);
      END IF;
      IF err_y < to_signed(16#00000000#, 16) THEN 
        err_y_0(s_idx) :=  - (resize(err_y, 17));
        IF (err_y_0(s_idx)(16) = '0') AND (err_y_0(s_idx)(15) /= '0') THEN 
          err_y := X"7FFF";
        ELSIF (err_y_0(s_idx)(16) = '1') AND (err_y_0(s_idx)(15) /= '1') THEN 
          err_y := X"8000";
        ELSE 
          err_y := err_y_0(s_idx)(15 DOWNTO 0);
        END IF;
      END IF;
      IF err_y > to_signed(16#000003E8#, 16) THEN 
        err_y := to_signed(16#03E8#, 16);
      END IF;
      add_temp_3(s_idx) := resize(err_x, 17) + resize(err_y, 17);
      IF (add_temp_3(s_idx)(16) = '0') AND (add_temp_3(s_idx)(15) /= '0') THEN 
        cast_4(s_idx) := X"7FFF";
      ELSIF (add_temp_3(s_idx)(16) = '1') AND (add_temp_3(s_idx)(15) /= '1') THEN 
        cast_4(s_idx) := X"8000";
      ELSE 
        cast_4(s_idx) := add_temp_3(s_idx)(15 DOWNTO 0);
      END IF;
      mul_temp_2(s_idx) := cast_4(s_idx) * 15;
      IF (mul_temp_2(s_idx)(31) = '0') AND (mul_temp_2(s_idx)(30 DOWNTO 15) /= X"0000") THEN 
        add_cast_0(s_idx) := X"7FFF";
      ELSIF (mul_temp_2(s_idx)(31) = '1') AND (mul_temp_2(s_idx)(30 DOWNTO 15) /= X"FFFF") THEN 
        add_cast_0(s_idx) := X"8000";
      ELSE 
        add_cast_0(s_idx) := mul_temp_2(s_idx)(15 DOWNTO 0);
      END IF;
      add_cast_1(s_idx) := resize(add_cast_0(s_idx), 17);
      add_cast_2(s_idx) := resize(tmp & '0', 48);
      add_cast_3(s_idx) := add_cast_2(s_idx)(15 DOWNTO 0);
      add_temp_4(s_idx) := add_cast_1(s_idx) + resize(add_cast_3(s_idx), 17);
      IF (add_temp_4(s_idx)(16) = '0') AND (add_temp_4(s_idx)(15) /= '0') THEN 
        A := X"7FFF";
      ELSIF (add_temp_4(s_idx)(16) = '1') AND (add_temp_4(s_idx)(15) /= '1') THEN 
        A := X"8000";
      ELSE 
        A := add_temp_4(s_idx)(15 DOWNTO 0);
      END IF;
      IF A < minA THEN 
        minA := A;
        best_str := resize(nc(s_idx), 16);
      END IF;
    END LOOP;

    -- --- Accel branch: 8 speed terms ---
    minB := to_signed(16#7FFF#, 16);
    best_acc := to_signed(16#0000#, 16);

    FOR a_idx IN 0 TO 7 LOOP
      add_temp_1(a_idx) := resize(v_signed, 17) + resize(nc_0(a_idx), 17);
      IF (add_temp_1(a_idx)(16) = '0') AND (add_temp_1(a_idx)(15) /= '0') THEN 
        v_next := X"7FFF";
      ELSIF (add_temp_1(a_idx)(16) = '1') AND (add_temp_1(a_idx)(15) /= '1') THEN 
        v_next := X"8000";
      ELSE 
        v_next := add_temp_1(a_idx)(15 DOWNTO 0);
      END IF;
      IF v_next > to_signed(16#00000280#, 16) THEN 
        v_next := to_signed(16#0280#, 16);
      END IF;
      IF v_next < to_signed(16#00000000#, 16) THEN 
        v_next := to_signed(16#0000#, 16);
      END IF;
      sub_temp_1(a_idx) := resize(v_next, 17) - resize(ref_v_signed, 17);
      IF (sub_temp_1(a_idx)(16) = '0') AND (sub_temp_1(a_idx)(15) /= '0') THEN 
        ov := X"7FFF";
      ELSIF (sub_temp_1(a_idx)(16) = '1') AND (sub_temp_1(a_idx)(15) /= '1') THEN 
        ov := X"8000";
      ELSE 
        ov := sub_temp_1(a_idx)(15 DOWNTO 0);
      END IF;
      IF ov < to_signed(16#00000000#, 16) THEN 
        ov := to_signed(16#0000#, 16);
      END IF;
      IF ov > to_signed(16#000000FF#, 16) THEN 
        ov := to_signed(16#00FF#, 16);
      END IF;
      IF v_next > ref_v_signed THEN 
        v_next := ref_v_signed;
      END IF;
      mul_temp_3(a_idx) := ov * to_signed(16#00000006#, 32);
      sub_cast_3(a_idx) := mul_temp_3(a_idx)(15 DOWNTO 0);
      sub_cast_4(a_idx) := resize(v_next & '0', 32);
      IF (sub_cast_4(a_idx)(31) = '0') AND (sub_cast_4(a_idx)(30 DOWNTO 15) /= X"0000") THEN 
        sub_cast_5(a_idx) := X"7FFF";
      ELSIF (sub_cast_4(a_idx)(31) = '1') AND (sub_cast_4(a_idx)(30 DOWNTO 15) /= X"FFFF") THEN 
        sub_cast_5(a_idx) := X"8000";
      ELSE 
        sub_cast_5(a_idx) := sub_cast_4(a_idx)(15 DOWNTO 0);
      END IF;
      sub_cast_6(a_idx) := resize(sub_cast_5(a_idx), 17);
      sub_temp_2(a_idx) := resize(sub_cast_3(a_idx), 17) - sub_cast_6(a_idx);
      IF (sub_temp_2(a_idx)(16) = '0') AND (sub_temp_2(a_idx)(15) /= '0') THEN 
        B := X"7FFF";
      ELSIF (sub_temp_2(a_idx)(16) = '1') AND (sub_temp_2(a_idx)(15) /= '1') THEN 
        B := X"8000";
      ELSE 
        B := sub_temp_2(a_idx)(15 DOWNTO 0);
      END IF;
      IF B < minB THEN 
        minB := B;
        best_acc := resize(nc_0(a_idx), 16);
      END IF;
    END LOOP;

    accel_cmd_tmp <= best_acc;
    steer_cmd_tmp <= best_str;
  END PROCESS fcs_mpc_v4_1_output;


  accel_cmd <= std_logic_vector(accel_cmd_tmp);

  steer_cmd <= std_logic_vector(steer_cmd_tmp);

END rtl;

